export const EventConstant = {

    ADD_CONNECTION : "ADD_CONNECTION",

    TEST_CONNECTION : "TEST_CONNECTION",

    EDIT_CONNECTION : "EDIT_CONNECTION",

    DELETE_CONNECTION : "DELETE_CONNECTION"
}