export const EventConstant = {

    ADD_CONNECTION: "ADD_CONNECTION",

    TEST_CONNECTION: "TEST_CONNECTION",

    EDIT_CONNECTION: "EDIT_CONNECTION",

    DELETE_CONNECTION: "DELETE_CONNECTION",

    TO_CONTROL_DASHBOARD: "TO_CONTROL_DASHBOARD",

    UNSUBSCRIBE_ALL: "UN_SUBSCRIBE_ALL_",

    SUBSCRIBE_ALL: "SUBSCRIBE_ALL_",

    SUBSCRIBE: "SUBSCRIBE_",

    UNSUBSCRIBE: "UNSUBSCRIBE_",

    DISCONNECTION: 'DISCONNECTION_',

    NOTIFY_SUBSCRIBE: 'NOTIFY_SUBSCRIBE',

    PUBLICATION : 'PUBLICATION_',

    REQUEST : 'REQUEST_',
}